name: black_queen
description: Black Queen card game
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <5.0.0'

dependencies:
  flutter:
    sdk: flutter

  web_socket_channel: ^3.0.3
  shared_preferences: ^2.3.3
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/cards/
