name: black_queen
description: Black Queen card game
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  web_socket_channel: ^3.0.3
  shared_preferences: ^2.5.3

flutter:
  uses-material-design: true
  assets:
    - assets/cards/
